### ISSUE TITLE
Warn on cookie length? 

### ISSUE THREAD

**Issue by seanislegend** [vvo/next-iron-session#101]
I've just spent a little while debugging an issue with the cookie not being saved as expected. Upon inspection I realised that the API I was working with started returning more information, thus exceeding the cookie byte limit.

Although that issue is on me, if someone else was to run into it, having a warning on cookie size (even dev only) would have reduce the debugging time.

Great work so far!

**Comment by vvo** [comment]
@seanislegend that's the kind of great feedback I was expecting from people using this module. Do you happen to know if it was the browser that was refusing the cookie or any other piece of code inside next-iron-session? I will have a try at replicating this but if you have more information, let me know :)

**Comment by seanislegend** [comment]
Great to hear. I'm afraid that at the moment I realised, I didn't have enough time to take a deeper dive into the root of the issue. Happy to throw together a reproducible repo for you in the mean time, if that helps.

**Comment by vvo** [comment]
@seanislegend Yes that would help me a lot indeed, if you have some time

**Comment by seanislegend** [comment]
I have duplicated the Next.js example folder and included a reproduction here:
https://github.com/seanislegend/next-iron-session-byte-exceeded-bug/blob/master/pages/api/login.js#L11-L254

The change I made is storing additional data in the session. Let me know if there's anything else I can do to help.

**Comment by vvo** [comment]
Thanks for reproducible code @seanislegend!
