### ISSUE TITLE
BUG | .flat is not a function when using in a typescript project?

### ISSUE THREAD

**Issue by louisgv** [vvo/next-iron-session#125]
Got this weird behavior when using this library in a typescript nextjs project:

```
TypeError: [(res.getHeader(...) || [])].flat is not a function
    at Object.save (...\node_modules\next-iron-session\dist\index.js:82:69)
```

**Comment by louisgv** [comment]
Found the issue. My nodejs version on this box was old (10.x), and flat was not a thing.

Maybe add a note in the readme that this library only work on node>12

**Comment by vvo** [comment]
Thanks, just updated the Node.js version requirements
