### ISSUE TITLE
Unset vs. destroy in terms of security

### ISSUE THREAD

**Issue by calspre** [vvo/next-iron-session#126]
Hi! Thanks for authoring this useful library. Quick question -- In [usage](https://github.com/vvo/next-iron-session#usage) `destroy()` is called when signing out, but is it okay to use `unset('user')` instead? Are there any security concerns I should be aware of?

FYI, I want to store other data via `set('someKeyOtherThanUser')` but it seems that calling `destroy()` would clear out both `'user'` and `'someKeyOtherThanUser'` I want to clear only the `'user'` data when signing out.

**Comment by vvo** [comment]
Hey there,it’s definitely fine to use unset for logout indeed. No security issue compared to destroy. Thanks for using the library!

**Comment by calspre** [comment]
Thanks!
