### ISSUE TITLE
Is it secure to detect whether user is signed in based on whether session could be retrieved?

### ISSUE THREAD

**Issue by jensmeindertsma** [vvo/next-iron-session#149]
I'm using Next.js with API routes to handle authentication. I have a `/api/signin` endpoint that is called from the frontend with `email` and `password`. When the user password & email are correct, a session is set & saved on the request with `req.session.set` and `req.session.save`. I can't store all of the user data in the cookie because it would be too large, so instead I send back a JSON response with all the user data and just set the user ID in the cookie. 

When a user wants to update their information, the frontend calls `/api/update` with the updated information. The API route will save the changes to the database, but will need to verify that the user is authenticated first. 

Is it secure to just check whether `req.session.get("user")` returns an object that contains an ID? 

I thought about this,  but I'm not sure. The session is encrypted and decrypted using a _secret_ password so in theory nobody could set a "fake" session on the request with any user ID. Only users that have signed in using our application ( submitted the right email and password to `/api/signin` ) should have a session that is decryptable by `req.session.get`. Am I right? I would tremendously appreciate to hear from you, I can't find any resources on this.

**Comment by vvo** [comment]
> Is it secure to just check whether `req.session.get("user")` returns an object that contains an ID?
> Am I right?

Yes, this is sufficient. As there's no way for someone to tamper with the cookie data (i.e. changing the logged in user id for example).

But you still have to check if the user is active or not, so that if someone steals this user cookie for example if the person was hacked then you have to have a way to deactivate the user in your database (like deactivated = true/false).

Then on every API request you can: get the user with a `where deactivated = false` and you'll be good.

This is what I do!

**Comment by jensmeindertsma** [comment]
Nice! I think you mean I should check with for example Firebase Admin whether the user corresponding to the ID on the session exists and is active?

**Comment by jensmeindertsma** [comment]
Thanks so much for your help!

**Comment by vvo** [comment]
> I think you mean I should check with for example Firebase Admin whether the user corresponding to the ID on the session exists and is active?

Yes, you should never trust JUST the session, always check in your database if this particular user exists and has access to the resource they're asking for. Good luck!

**Comment by jensmeindertsma** [comment]
Well, since the API routes have a serverless nature, I would need to re-authenticate the user with email and password every time I want to get some of their data if I want to make sure they only get data they have access to. 

Instead, can I, after getting the ID from the session and making sure whether the user is not deactivated, get the data with for example Firebase Admin. I'd only get the data corresponding to the user ID in the session. Thanks!

**Comment by vvo** [comment]
> Instead, can I, after getting the ID from the session and making sure whether the user is not deactivated, get the data with for example Firebase Admin? It seems safe to me! I'd only get the data corresponding to the user ID in the session.

Yes it's safe :)

**Comment by jensmeindertsma** [comment]
Thanks, have a nice day!
