### ISSUE TITLE
Need example for additional authenticated API calls

### ISSUE THREAD

**Issue by lww** [vvo/next-iron-session#157]
Hi, in the example project I want to make additional requests only if a user is logged in.

Would you recommend adding another hook, for example `useMovies()` and pass in the user object?

```
const { user } = useUser({ redirectTo: '/login' })
const { movies } = useMovies()
```

As far as I understand, useMovies would still be called in the beginning, even if there is no user.
How would you write the hook then, to only fetch when user logged in?

Or is there a better way?

**Comment by vvo** [comment]
Hi there, your question is more about how to use SWR: https://github.com/zeit/swr and specifically what they call "dependent fetching": https://github.com/vercel/swr#dependent-fetching.

I added an example in the repository still, see: https://github.com/vvo/next-iron-session/commit/f0442225fa14913da4f356265de22da90d991d5f

Going further: What I recommend, if all your application dashboard relies on the user being present, is to useUser in your Layout directly and show either an application empty skeleton (like: https://www.smashingmagazine.com/2020/04/skeleton-screens-react/) or just a simple "Loading..." as for the main content of the app and anything that depends on the user.

Once you got the user, you can continue displaying your Layout that relies on user being present and add more swr calls to it.

Hope this helps!

**Comment by lww** [comment]
Hi @vvo, sorry I didn't see your response before. :grimacing:
You were right, I didn't know enough about swr.

Thanks for adding the example and the tips about empty skeleton,
maybe it will be useful for other people as well! :yellow_heart:

**Comment by vvo** [comment]
No prob :) Enjoy!
