### ISSUE TITLE
Sharing cookie across subdomains

### ISSUE THREAD

**Issue by kennethacohen** [vvo/next-iron-session#161]
Is there any way to access the `domain` property on the underlying cookie that gets created? I have a use case where a user should stay authenticated across subdomains. Example is that a subdomain = a storefront, but if a user is auth'd in a given storefront, that should hold across all subdomains.

Thanks in advance!

**Comment by vvo** [comment]
> Is there any way to access the `domain` property on the underlying cookie that gets created?

Yes, you can pass your own domain option like this:

```js
import { withIronSession } from "next-iron-session";

async function handler(req, res) {
  // get user from database then:
  req.session.set("user", {
    id: 230,
    admin: true,
  });
  await req.session.save();
  res.send("Logged in");
}

export default withIronSession(handler, {
  password: "complex_password_at_least_32_characters_long",
  // if your localhost is served on http:// then disable the secure flag
  cookieOptions: {
    secure: process.env.NODE_ENV === "production",
    domain: "estore.com" // this will allow all sub domains of estore.com
  },
});
```

Let me know if this works for you.

**Comment by kennethacohen** [comment]
Thanks! I think the `cookieOptions` type definition just needs to be extended to support all of these options.

**Comment by vvo** [comment]
I am not using TypeScript but that's a good idea! If you have the knowledge and the will to do so, please open a pull request! Tanks :)
