### ISSUE TITLE
Error: Incorrect number of sealed components

### ISSUE THREAD

**Issue by louisgv** [vvo/next-iron-session#183]
I'm getting this error suddenly, very weird. This is a 500 so it seems my next API route is broken, but no error/broken build. Next still saying compile successful. I have found that using incognito bypass the problem.

**Comment by louisgv** [comment]
Seems to stem from https://npmdoc.github.io/node-npmdoc-iron/build/apidoc.html

**Comment by louisgv** [comment]
So I found the cause of the error. Another app apparently created cookie under the same name, so iron could not parse it. Feel free to close!

**Comment by vvo** [comment]
Indeed this is why nowadays we recommend setting a very specific cookieName and enforcing its usage. When you have two cookies with the exact same name and the url of the website is the same then you can have issues. This happens a lot in development, https://localhost:3000 can be many apps so be sure to use a cookieName that's always different for each app.

**Comment by dalalRohit** [comment]
#380
