### ISSUE TITLE
Next.js - Getting Error [ERR_HTTP_HEADERS_SENT]

### ISSUE THREAD

**Issue by develanet** [vvo/next-iron-session#221]
This is based off of the example for next.js 
```

export const getServerSideProps = withSession(
  async ({ req, res, query }) => {
    const user = req.session.get('user');

    if (!user) {
      res.setHeader('location', '/login');
      res.statusCode = 302;
      res.end();
      return { props: {} };
    }

//... rest of code ...//

})
```

Full Error:

```
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:518:11)
    at DevServer.sendHTML (/Users/zay/Code/node_modules/next/dist/server/next-dev-server.js:35:5)
    at DevServer.render (/Users/zay/Code/node_modules/next/dist/next-server/server/next-server.js:56:37)
    at async Object.fn (/Users/zay/Code/node_modules/next/dist/next-server/server/next-server.js:31:107)
    at async Router.execute (/Users/zay/Code/node_modules/next/dist/next-server/server/router.js:23:67)
    at async DevServer.run (/Users/zay/Code/node_modules/next/dist/next-server/server/next-server.js:49:494)
    at async DevServer.handleRequest (/Users/zay/Code/node_modules/next/dist/next-server/server/next-server.js:17:101) {
  code: 'ERR_HTTP_HEADERS_SENT'
}
```

Is there something I may be doing wrong or an issue withSession?

**Comment by vvo** [comment]
Hi there, could you create a GitHub repository where I could reproduce the issue? Could it be that there's someplace trying to save the session after you already replied to the user? Thanks!

**Comment by humayunj** [comment]
Hey, this issue seems related to nextjs itself, there's a discussion [RFC: Returning redirects from getServerSideProps / getStaticProps](https://github.com/vercel/next.js/discussions/14890)

**Comment by vvo** [comment]
Weirdly the example from this repository (ssr example I believe) is working well. I am only using static generation though, not ssr in my apps

**Comment by vvo** [comment]
@develanet or @humayunj if you can reproduce this issue and create a repository out of it, I can help

**Comment by mrgoonie** [comment]
I can confirm this error can be **sometime happened** when you redirect on SSR using `res.setHeader(....)`

`Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client`

I don't think the problem is with `next-iron-session` but Next.js framework behavior itself... 

https://github.com/vercel/next.js/discussions/14890

**Comment by develanet** [comment]
@vvo Thanks for your response but I am going with a different approach on this one.

**Comment by rubyjasmin** [comment]
Also had this issue and drove myself crazy for hours implementing all the solutions online to no avail, walked away came back and realized I left the `await` out of `await res.session.save();`
