### ISSUE TITLE
getServerSideProps duplicate code in each page

### ISSUE THREAD

**Issue by msreekm** [vvo/next-iron-session#268]
@vvo , Bonjour! Thanks for the next-iron-session example .

Any ideas on removing below duplicate code in each getServerSideProps for SSR pages ? 

const user = req.session.get('user')
if (user === undefined) {
res.setHeader('location', '/login')
res.statusCode = 302
res.end()
return { props: {} }
}
-----------------------------
something like this- 
//profile-ssr.js
export const getServerSideProps = withSession(async function (ctx) {
  const { req } = ctx;
  const user = RedirectIfNotAuthenticated(ctx);
  if (!user) {
    return { props: {} };
  }
  return {
    props: { user: req.session.get("user") },
  };
});

//session.js
export function RedirectIfNotAuthenticated({ req, res }) {
  const user = req.session.get("user");
  if (user === undefined) {
    res.setHeader("location", "/login");
    res.statusCode = 302;
    res.end();
    return false;
  }
  return true;
}

**Comment by pedrojimenezp** [comment]
@msreekm You can create something like a `withSession` function outside and then import it wherever you need it, like in the example for next.js:

https://github.com/vvo/next-iron-session/blob/master/examples/next.js/lib/session.js

https://github.com/vvo/next-iron-session/blob/master/examples/next.js/pages/profile-ssr.jsx

**Comment by pedrojimenezp** [comment]
@msreekm  This is what I'm doing:

`withSession.js`
```js
// this file is a wrapper with defaults to be used in both API routes and `getServerSideProps` functions
import { withIronSession } from 'next-iron-session';

export const sessionOptions = {
  password:
    process.env.SECRET_COOKIE_PASSWORD ||
    'some-really-long-password-with-32-bites-minimum',
  cookieName: 'my-awesome-cookie-name',
  cookieOptions: {
    // the next line allows to use the session in non-https environements like
    // Next.js dev mode (http://localhost:3000)
    secure: process.env.NODE_ENV === 'production',
  },
};

export default function withSession(handler) {
  return withIronSession(handler, sessionOptions);
}
```

`withAuth.js`
```js
import withSession from './session';

function _withAuth(handler) {
  return async (context) => {
    const { req } = context;

    const user = req.session.get('user');
    if (!user) {
      // 'redirecting to /login because there is not user'
      return {
        redirect: {
          destination: '/login',
          permanent: false,
        },
      };
    }

    const newCtx = {
      ...context,
      user,
    };

    return handler(newCtx);
  };
}

export default function withAuth(handler) {
  return withSession(_withAuth(handler));
}
```
After creating the `withAuth` function, you just need to use it in all the pages that require authentication, like the following one:

`dashboard.js`
```js
import withAuth from './auth';

export default function Dashboard(props) {
  return (
    <div>
      This is a private view, you can see it only if you are authenticated
    </div>
  );
}

export const getServerSideProps = withAuth(async (context) => {
  const { user } = context;
  return { props: {  user  } };
});
```

Let me know if that works for you

**Comment by msreekm** [comment]
WiIll give it a try ,looks good to me!  it does eliminate duplicate code in each page!

**Comment by vvo** [comment]
Nice, would be awesome, if you want to, to update the example of this repository to use that.

**Comment by pedrojimenezp** [comment]
@vvo Sure! I will create a PR to update the example this weekend

**Comment by vvo** [comment]
hi @pedrojimenezp any time you can submit an update to the README and examples to showcase how to get the context would be ... awesome! Thanks :)

**Comment by vvo** [comment]
Thanks for the ideas and solution, this is a generic Next.js question though now.
