### ISSUE TITLE
login fails on production build

### ISSUE THREAD

**Issue by hanssl** [vvo/next-iron-session#272]
I noticed some intermittent problems in the dev build (sometimes a successful login would not redirect as it should) so I tried the production build and it always fails.

Steps to reproduce:
1. npx create-next-app --example with-iron-session with-iron-session-app
2. cd with-iron-session-app
3. npm run build && npm run start
4. open a browser to localhost:3000/login
5. enter a valid github username and submit
6. observe that the login page does not change state.

**Comment by hanssl** [comment]
I figured out my issue.  In a production build the cookie includes the 'secure' option which prohibits the cookie on a non HTTPS server.

**Comment by vvo** [comment]
Thanks, might have to address that issue, has mentioned here: https://github.com/vvo/next-iron-session/issues/272. If you want to have a try, go!
