### ISSUE TITLE
Hello~

### ISSUE THREAD

**Issue by vvo** [vvo/next-iron-session#281]
Hello~
 I'm learning web development. I am using next-iron-session and get the message: Missing password parameter even if I have set SECRET_COOKIE_PASSWORD in the .env file. I would like to knwo what could be the cause of the error.

_Originally posted by @pkabore in https://github.com/vvo/next-iron-session/issues/130#issuecomment-748340212_

**Comment by vvo** [comment]
Hi @pkabore you'll get more help by opening a new issue, but just in case, setting only the env variable is not sufficient you also have to pass it to your code.

I suggest you double check this documentation: nextjs.org/docs/basic-features/environment-variables

**Comment by pkabore** [comment]
great! I'll do it then.
