### ISSUE TITLE
Missing parameter password

### ISSUE THREAD

**Issue by pkabore** [vvo/next-iron-session#283]
I used the nextjs example of next-iron-session, and set the SECRET_COOKIE_PASSWORD in the .env but whenever I try to do a login I get the Missing parameter password error.

I checked in the /lib/session.js and it is using `process.env.SECRET_COOKIE_PASSWORD` as well.
I don't have an idea of where else again I have to pass a password parameter.

this is the /lib/session.js file.

// this file is a wrapper with defaults to be used in both API routes and `getServerSideProps` functions
```import { withIronSession } from "next-iron-session";

export default function withSession(handler) {
  return withIronSession(handler, {
    password: process.env.SECRET_COOKIE_PASSWORD,
    cookieName: "next-iron-session/session/next.js",
    cookieOptions: {
      // the next line allows to use the session in non-https environements like
      // Next.js dev mode (http://localhost:3000)
      secure: process.env.NODE_ENV === "production",
    },
  });
}
```

**Comment by vvo** [comment]
Do a console.log(process.env.SECRET_COOKIE_PASSWORD) just before passing it down to next-iron-session and see if it contains a value. If no then you should learn/read on how to use env variables in your Next.js code (https://nextjs.org/docs/basic-features/environment-variables)
