### ISSUE TITLE
Authentication for wss

### ISSUE THREAD

**Issue by felri** [vvo/next-iron-session#295]
Hello, thanks for this awesome lib!

I'm using next-iron-session but with a custom server to handle wss requests

https://nextjs.org/docs/advanced-features/custom-server

After the user authenticate I can move between protected routes perfectly, but I need to check if the user is logged in when he tries to connect to the websocket session.

My serve.js is the following

```js
const { createServer } = require('http');
const { parse } = require('url');
const next = require('next');
const WebSocket = require('ws');
const http = require('http');

const wss = new WebSocket.Server({ clientTracking: false, noServer: true });

const dev = process.env.NODE_ENV !== 'production';
const app = next({ dev });
const handle = app.getRequestHandler();

const server = http.createServer(app);

server.on('upgrade', async function (request, socket, head) {
  console.log('Parsing session from request...');

  //>>>>>>>>>>>>>>>>>>>something needs to happen here to get the session and check if everything is ok<<<<<<<<<<<<<<<<

  if (!request.session.user) {
    socket.write('HTTP/1.1 401 Unauthorized\r\n\r\n');
    socket.destroy();
    return;
  }

  wss.handleUpgrade(request, socket, head, function (ws) {
    wss.emit('connection', ws, request);
  });
});

wss.on('connection', function (ws, request) {
  const user = request.session.user.cpf;

  map.set(user, ws);

  ws.on('message', function (message) {
    console.log(`Received message ${message} from user ${user}`);
  });

  ws.on('close', function () {
    map.delete(user);
  });
});

app.prepare().then(() => {
  createServer((req, res) => {
    // Be sure to pass `true` as the second argument to `url.parse`.
    // This tells it to parse the query portion of the URL.
    const parsedUrl = parse(req.url, true);

    handle(req, res, parsedUrl);
  }).listen(3000, (err) => {
    if (err) throw err;
    console.log('> Ready on http://localhost:3000');
  });
});

server.listen(3232, function () {
  console.log('Websockerts listening on http://localhost:3232');
});

```

The important part is that when I receive a request in a certain port, the server needs to check if the user is logged in: 

```js
server.on('upgrade', async function (request, socket, head) {
  console.log('Parsing session from request...');

  //>>>>>>>>>>>>>>>>>>>something needs to happen here to get the session and check if everything is ok<<<<<<<<<<<<<<<<

  if (!request.session.user) {
    socket.write('HTTP/1.1 401 Unauthorized\r\n\r\n');
    socket.destroy();
    return;
  }

  wss.handleUpgrade(request, socket, head, function (ws) {
    wss.emit('connection', ws, request);
  });
});
```

This is the documentation part of the wss lib
https://github.com/websockets/ws#client-authentication

Anyone has a clue of how can I check if the user is logged in in this scenario?

**Comment by vvo** [comment]
I did not reply but truth to be told: I have no idea how to handle cookie auth in a websocket.

Maybe those pages can help: https://coletiv.com/blog/using-websockets-with-cookie-based-authentication/.

**Comment by zackify** [comment]
Here's how I did it! First off, thanks so much to @vvo for making a low level library so that we can parse the cookie data.

```js
import ironStore from "iron-store";

...

 onConnect: async (cnxnParams, webSocket, cnxnContext) => {
      // name of the cookie you used for ironSession
      let { userAuth } = cookie.parse(
        webSocket.upgradeReq.headers.cookie || ""
      );
      const store = await ironStore({
        // same password from your ironSession
        password: process.env.SECRET_COOKIE_PASSWORD as string,
        sealed: userAuth,
      });
      // get the data the same way you are used to
      const user = store.get("user");

      return {
        user,
      };
    },
```

Essentially, i send cookies with the websocket upgrade request. When the websocket starts a connection, I can parse out the cookie and manually initialize it.

**Comment by vvo** [comment]
@zackify Would you be so kind and add a small section to the README on how to authenticate other parts of your application using iron-store? Thanks! Actually, any token generated by next-iron-session can be decoded with https://github.com/hapijs/iron (and its ports: https://github.com/hapijs/iron/issues?q=label%3Aport+is%3Aclosed+sort%3Aupdated-desc)

**Comment by baristikir** [comment]
> Here's how I did it! First off, thanks so much to @vvo for making a low level library so that we can parse the cookie data.
> 
> ```js
> import ironStore from "iron-store";
> 
> ...
> 
>  onConnect: async (cnxnParams, webSocket, cnxnContext) => {
>       // name of the cookie you used for ironSession
>       let { userAuth } = cookie.parse(
>         webSocket.upgradeReq.headers.cookie || ""
>       );
>       const store = await ironStore({
>         // same password from your ironSession
>         password: process.env.SECRET_COOKIE_PASSWORD as string,
>         sealed: userAuth,
>       });
>       // get the data the same way you are used to
>       const user = store.get("user");
> 
>       return {
>         user,
>       };
>     },
> ```
> 
> Essentially, i send cookies with the websocket upgrade request. When the websocket starts a connection, I can parse out the cookie and manually initialize it.

I'm getting an error when I try it with `iron-store`. I have checked if the cookie is there and indeed thats the case. But somehow my store is throwing an error. 
```bash
Error: Bad hmac value at Object.exports.unseal (/workspace/api/node_modules/@hapi/iron/lib/index.js:311:15)
```

I am using the same password like in the `ironSession` and passing the cookie value as sealed.
Has someone experienced the same and may know a solution for this?
