### ISSUE TITLE
req.session.destroy() doesn't delete cookie

### ISSUE THREAD

**Issue by Deivaras** [vvo/next-iron-session#309]
Cookie not being deleted on logout click when deployed on Vercel. Used with your example from:
https://github.com/vercel/next.js/tree/canary/examples/with-iron-session
"dependencies": {
    "next": "10.0.6",
    "next-iron-session": "4.1.11",
    "prop-types": "15.7.2",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "swr": "0.4.2"
  },

All happening on random basis with a random sequence. Login (1), Logout (1), Login (2), Logout (2) - fail, Logout (3) - fail...
Sometimes on login cookie being set but UI doesn't change, after you click login second time, cookie being rewritten and then you get logged in.
Results differ with : 

- Google Chrome @Version 88.0.4324.150 (Official Build) (64-bit)
- Firefox @85.0.2 (64-bit)

Also your example at https://next-iron-session.now.sh/
is not working (on random basis) on Google Chrome:
TypeError: Cannot read property 'type' of undefined
    at SEwE.t.default (profile-sg-b75f51d20ee90d0df268.js:1)
    at ro (framework.9d524150d48315f49e80.js:1)
    at jo (framework.9d524150d48315f49e80.js:1)
    at Qu (framework.9d524150d48315f49e80.js:1)
    at Pi (framework.9d524150d48315f49e80.js:1)
    at xi (framework.9d524150d48315f49e80.js:1)
    at _i (framework.9d524150d48315f49e80.js:1)
    at vi (framework.9d524150d48315f49e80.js:1)
    at framework.9d524150d48315f49e80.js:1
    at t.unstable_runWithPriority (framework.9d524150d48315f49e80.js:1)

On FIrefox trying to logout gives:
GEThttps://next-iron-session.now.sh/api/events
[HTTP/2 401 Unauthorized 165ms]

SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data

UPDATE: 
when I set disable cache on Chrome dev tools everything is working perfect.

**Comment by vvo** [comment]
Hey there I believe this is now fixed in the live example, can you have a look? At least I am not able to reproduce it.

**Comment by Deivaras** [comment]
You are my hero! Thank you. Seems everything fine now, both on Chrome and Firefox.
