### ISSUE TITLE
One of the reference links in the README is out of date

### ISSUE THREAD

**Issue by fcFn** [vvo/next-iron-session#327]
Hi!

The link to [`https://owasp.org/www-project-cheat-sheets/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html#encryption-based-seal-pattern`](https://owasp.org/www-project-cheat-sheets/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html#encryption-based-seal-pattern) appears to be out of date. I couldn't find anything related to a seal there. Perhaps it should be updated?

**Comment by vvo** [comment]
Thanks, I believe this moved here: https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html#encryption-based-token-pattern

(seal => token)

updating the readme now.

**Comment by rporrasluc** [comment]
I think the link is outdated again. Could you please point to the documentation that could be checked regarding this? Not clear for me if this library implements/adds any CSRF protection. I think no much more apart from SameSite attribute implicit protection which is not enough as not all browsers support it. Any guidance/documentation about how to properly implement such protection?

I guess I could do a first request to get a CSRF token created in the session and get it back and persist it in a variable, hidden field, meta element, etc. and send it later when doing requests to API protected endpoints by sending it as part of the request headers.

I would have to check in the handler or in a middleware created for such purpose.

How does it sound? Thanks.

**Comment by vvo** [comment]
Hey @rporrasluc this library does not implement CSRF tokens automatically.

If you find ways to forge attacks to websites using next-iron-session I am very interested in your findings. I am no security nor auth expert at all. This may sound scary because I built next-iron-session but this is the reality. I made everything so that the attack surfaces should be low but there's always a way I guess.

**Comment by vvo** [comment]
This page explains it well I would say: https://portswigger.net/web-security/csrf/samesite-cookies

**Comment by vvo** [comment]
Just updated the link here: https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html#samesite-cookie-attribute

**Comment by rporrasluc** [comment]
Thanks @vvo , I pretty much know how same site attribute works. However, this attribute is a protection led by the browser, and not all browsers support it. It's quite well described here:

https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html#samesite-cookie-attribute

It's good to use same site attribute... but not enough by itself.

**Comment by vvo** [comment]
You're right, I did not implement CSRF tokens at all because to be honest I did not know exactly what to do. For my own websites, I am fine with the way it is today.

If you find a no-too-complex way to have better csrf protection with Next.js and next iron session please report back. Good luck

**Comment by rporrasluc** [comment]
Thanks @vvo. Will let you know if I figure out something, thank you for the work on this great library.
