### ISSUE TITLE
Unable to parse cookie: TypeError: argument str must be a string

### ISSUE THREAD

**Issue by vincentducorps** [vvo/next-iron-session#35]
Hello,

I have this error when I run the example:

```bash
TypeError: argument str must be a string
    at Object.parse (C:\Users\vducorps\Development\next-iron-session\example\node_modules\cookie\index.js:51:11)
    at withIronSessionHandler (C:\Users\vducorps\Development\next-iron-session\example\node_modules\next-iron-session\dist\index.js:53:31)

[...]
```

https://github.com/vvo/next-iron-session/blob/ae1dd6a2cfe2d20add4666e9f91213a5700db0e2/lib/index.js#L50

Do you have any idea why?
Looks like the cookie is not provided.

**Comment by vvo** [comment]
Hey I just git cloned the repository, then:
- cd example
- yarn
- yarn dev

and everything works

is there some difference with your setup?

**Comment by vvo** [comment]
ok got it to fail, will fix tomorrow morning, thanks!

**Comment by vvo** [comment]
Ok a fix is incoming and the lib will be released automatically, upgrade and let me know!

PS: You're the first real user of this library I guess, and you are named Vincent (BIG PLUS), please ask any question on this module and we can work together from there.

Thanks again for reporting the bug.
