### ISSUE TITLE
invalid json response body at http://localhost:3000/api/user/[object%20Object] reason: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by IlirBajrami** [vvo/next-iron-session#352]
Im using this example and trying to fetch the user from my mongodb database and login with that but i get this error: "invalid json response body at http://localhost:3000/api/user/[object%20Object] reason: Unexpected token < in JSON at position 0"

this is my code in `login.js` file: 

```
import fetchJson from "../../lib/fetchJson";
import withSession from "../../lib/session";
import { withIronSession } from "next-iron-session";
import { connectToDatabase } from "../../util/mongodb";

export default withSession(async (req, res) => {
  const { db } = await connectToDatabase();

  const { username } = await req.body;
  const foundUser = await db.collection("users").findOne({"userName": username});


  console.log(foundUser)
  
  const url = `http://localhost:3000/api/user/${foundUser}`;

  try {
   

    const { userName, email } = await fetchJson(url);
    const user = { isLoggedIn: true, userName, email }
    
    
    req.session.set("user", user);
    await req.session.save();
    res.json(user);
  } catch (error) {
    const { response: fetchResponse } = error;
    res.status(fetchResponse?.status || 500).json(error.data);
   
  }
});
```

in the console i get the user object (`foundUser`) just fine.

and this is my `user.js` file:

```
import withSession from "../../lib/session";
import { connectToDatabase } from "../../util/mongodb";

export default withSession(async (req, res) => {
  const user = req.session.get("user");

  
  if (user) {
    
    const { db } = await connectToDatabase();
    const foundUser = await db.collection("users").find({"userName": user.userName, "email": user.email});

    console.log("useri pi te user.js" + foundUser)
    
    // in a real world application you might read the user id from the session and then do a database request
    // to get more information on the user if needed


    
    res.json({
      
      isLoggedIn: true,
      ...user,
    });
  } else {
    res.json({
      isLoggedIn: false,
    });
  }
});

```

what am i doing wrong?

**Comment by vvo** [comment]
Hey there, most probably here:

> const url = `http://localhost:3000/api/user/${foundUser}`;

You should do something like foundUser.userName/email whatever you read.

You're sending http://localhost:3000/api/user/[object%20Object]  to your server so that's most probably the issue.

If you want more help, please open another issue with a reproducible example. Thanks!

**Comment by IlirBajrami** [comment]
Hi,
I tried that and i get the same error: `invalid json response body at http://localhost:3000/api/user/Beska reason: Unexpected token < in JSON at position 0`

here's a codesandbox with the whole code: https://codesandbox.io/s/quiet-lake-osyzm?file=/pages/api/login.js

**Comment by vvo** [comment]
Hey @IlirBajrami this sandbox is not working but for another reason than your current error (the iron session examples seems not to be compatible with codesandbox directly).

When invalid json response body happens, usually there's another response. Can you open your browser developer tools, go in the network tab and see what's inside the response?

Thanks

**Comment by IlirBajrami** [comment]
Hello Vincent, 
I didnt mean to bother you this long with my issue. maybe its a totally beginner thing but id like to use this authentication pattern with nextjs because it looks good and secure. maybe better than next-auth. 

heres my network tab output:

![Screenshot 2021-06-08 at 23 08 35](https://user-images.githubusercontent.com/22265824/121257901-89669c00-c8ae-11eb-8753-7edc21b12507.png)


regarding codesandbox, you should create a new terminal by clicking in the tiny + bottom right and run `npm run dev` there
<img width="1792" alt="Screenshot 2021-06-08 at 22 56 55" src="https://user-images.githubusercontent.com/22265824/121257081-9040df00-c8ad-11eb-8d1e-8dd8b8867d22.png">

Regards!
