### ISSUE TITLE
Cookies not being set

### ISSUE THREAD

**Issue by theahmadzai** [vvo/next-iron-session#364]
When using HTTP the cookies are not being set.

http://mysite.com (sends request)
https://mysite.com/api (sets cookie) no cookie appears on the browser but if the request is sent from HTTPS the cookie appears I have put redirect-SSL middleware on the API route but still not working.

Is there any alternative via next redirects/rewrites or some middleware for next-connect?

Thanks

**Comment by theahmadzai** [comment]
Solved the problem was something else

**Comment by quitequinn** [comment]
What was the problem?
