### ISSUE TITLE
typescript non-strict

### ISSUE THREAD

**Issue by akomm** [vvo/next-iron-session#369]
I just realized why so many errors in the typing could remain unnoticed. Its because you run on `strict: false`. No serious typescript project, except those migrating from pure JS to TS incrementally, will have it set to false, otherwise its totally pointless. 

Are there amy plans changing this? Also what makes some things to fix for strict now hard is the fact that you mutate objects like for example the request, making it harder to proper type it, wit hout copy & pasting vendor (next) types to adjust them, which makes code more prone to changes on nextjs side of typings. But I think changing this is due to huge BC break it would need is not to debate ;(

**Comment by vvo** [comment]
> Are there amy plans changing this?
No plans but definitely up for it. I wrote next-iron-session before I learned about TypeScript. I run on strict: true nowadays in my own projects. Even if I don't even know what it does yet.

> But I think changing this is due to huge BC break it would need is not to debate ;(

If you find a good new API that won't mutate the Next.js request object then I am all in yes as this would simplify things a lot yup.

Thanks again for jumping in on those subjects
