### ISSUE TITLE
Add applySession(req, res, options) method

### ISSUE THREAD

**Issue by vincentducorps** [vvo/next-iron-session#41]
Hello,

Can you add `applySession` method  just like https://github.com/hoangvvo/next-session#-applysession-

I prefer this approach (like in NextJS docs https://nextjs.org/docs/api-routes/api-middlewares) instead of `withSession`.

Thanks

**Comment by vvo** [comment]
@vincentducorps Aside from syntax difference, does using withSession works for you? If so could you explain a bit more with applySession is better for your usecase? Happy to learn more here, thanks!

**Comment by vvo** [comment]
Needs a clearer example/more explanation
