### ISSUE TITLE
Automatically save sessions without having to call req.session.save

### ISSUE THREAD

**Issue by vvo** [vvo/next-iron-session#52]
It is boring to have to type await req.session.save() everytime. It's clean because we're not monkey patching the res object but I think now is time to do it.

See https://github.com/hoangvvo/next-session autoCommit option and implementation

**Comment by hoangvvo** [comment]
Any update on this 😅 Seems like monkey patching the res object is really troublesome. Wondering if you have any alt solution.

**Comment by vvo** [comment]
> Any update on this 😅

Nope no update for now :D I've stick with explicit await save() calls for now in my own apps. In the end, I do not need so many of them (basically just login/logout..) so I might just stick with that and instead throw errors when the response was already sent.

> (I believe `iron` functions are async)

Yes indeed.

Too bad there's still no reliable way to hook into nodejs http response to add some headers without having to monkey patch everything...

On a side note, I wonder about the legitimacy of my own library since next-auth seems to be very advanced now (https://github.com/nextauthjs/next-auth#secure-by-default). Not sure though that you can even store session data inside the encrypted token (JWE), but maybe yes.

Good luck! Let me know of future updates :)

**Comment by vvo** [comment]
seems like everyone is fine with calling await, me included. less magic is good here
