### ISSUE TITLE
Make cookieName mandatory?

### ISSUE THREAD

**Issue by vvo** [vvo/next-iron-session#54]
When developing multiple websites on the same host (localhost:3000), then the cookieName and value can be shared between applications. While this is not a security issue (localhost), it's still annoying because it will lead to errors like "Error: Bad hmac value" because we're trying to decode appx cookie using the password of appy.

By making cookieName mandatory, we could avoid that and recommend to always use __appx __appy cookie names

**Comment by Dashue** [comment]
I'd be for this, just now trying to figure out where cookiename goes. Just installed the package and am not looking for intellisense for typescript, to then figure out where cookie name goes :)

**Comment by vvo** [comment]
@Dashue Do you mean that when using this package (thanks), your editor did not suggest the cookieName option? (https://github.com/vvo/next-iron-session#withironsessionhandler--password-ttl-cookiename-cookieoptions-)

I happen to be working on the package right now so I will just do that (make it mandatory)

**Comment by eric-burel** [comment]
Hi, what am I expected to do to fix this error? Add an explicit cookie name? I have this warning when running my Cypress e2e tests in headless mode, it might be a different issue, are there scenarios where the Hmac value cannot be computed? I couldn't find much documentation about this error
