### ISSUE TITLE
Cookie does not get removed after logout

### ISSUE THREAD

**Issue by dpyzo0o** [vvo/next-iron-session#64]
I played with the demo a little bit and I have noticed a strange behavior. After login, the cookie `next-iron-session/example` is set correctly. After I clicked logout, it did redirect me to login when I tried to access profile page. However I could still see the cookie from network panel. I supposed the cookie should be removed right?

**Comment by dpyzo0o** [comment]
<img width="1279" alt="Screen Shot 2020-04-20 at 18 48 24" src="https://user-images.githubusercontent.com/24768249/79743662-8a014380-8337-11ea-8ff3-7b268339eddd.png">

You can see that the cookie is still present in the network panel when I access the profile page after logout.

**Comment by dpyzo0o** [comment]
Just to mention, everything is working correctly, I just don't understand why the cookie is not removed after logout.

**Comment by vvo** [comment]
Hey there, just fixed it, you can remove await req.session.save() in logout, that's it!
