### ISSUE TITLE
Allow multiple passwords for key rotation

### ISSUE THREAD

**Issue by jperasmus** [vvo/next-iron-session#69]
Hi there, thanks for this module. 👋 

A small feature that I think will make it even better: please allow for multiple password keys to be set via an array (similar to how [`cookie-session`](https://www.npmjs.com/package/cookie-session#keys) does it). This would allow for passwords to be rotated without impacting existing sessions.

**Comment by jperasmus** [comment]
I think this might need to be added to the upstream `iron-store` module first.

**Comment by vvo** [comment]
@jperasmus Thanks for the comment, I was actually waiting for this request as I myself did not need it (or feels like I did not need it). The full implementation of rotating passwords can be tough on the user side (you have to generate and rotate them on your side and pass them down to the module). So I did not do it.

Now if you need it, yes it should be implemented in iron-store, I welcome a PR that would do so. The underlying iron feature is https://hapi.dev/module/iron/api/?v=6.0.0#await-sealobject-password-options so the changes may not be that hard (tests might be harder but we can work on that).

Give it a try and let me know

**Comment by vvo** [comment]
(working on this now)

**Comment by vvo** [comment]
@jperasmus This was implemented, see README and let me know how it goes. Do note that when upgrading to the new next-iron-session, previous sessions will be emptied (= logout). Now that the library contains password rotation built in though this is very unlikely to happen often.

**Comment by jperasmus** [comment]
Thank you so much! This is definitely going to help with rotating passwords while not messing with current sessions. 🧡
