### ISSUE TITLE
Usage with next-connect

### ISSUE THREAD

**Issue by Kerumen** [vvo/next-iron-session#70]
I try to use `next-connect` with [`next-iron-session`](https://github.com/vvo/next-iron-session/) but my API call stays in pending.

I don't know if the problem comes from this package or from the other, that's why I opened this issue and [another one](https://github.com/hoangvvo/next-connect/issues/46) in `next-connect`.

```js
function withSession(handler) {
  return withIronSession(handler, {
    password: process.env.SECRET_COOKIE_PASSWORD,
    cookieOptions: {
      secure: process.env.NODE_ENV === 'production' ? true : false,
    },
  })
}

const handler = nextConnect()

handler
  .use(withSession)
  .get(async (req, res) => {
    const user = req.session.get('user')
    res.json(user)
  })

export default handler
```

**Comment by Oxicode** [comment]
+1

**Comment by vvo** [comment]
(related to https://github.com/vvo/next-iron-session/issues/9)

Hi @Kerumen I see you got a reply in you other issue. This may be a documentation issue OR we might want to have a different API to handle this. If that's the case please open a PR!

**Comment by Kerumen** [comment]
Yes, thanks! Also it's pretty a duplicate of #9 now that I think about it. Sorry!
