### ISSUE TITLE
How would this be used with a Hapi powered API?

### ISSUE THREAD

**Issue by bonbonio** [vvo/next-iron-session#89]
I currently use JWT, how would I use this instead as it seems a better option for the static/server-side generation aspect of NextJS.

**Comment by vvo** [comment]
Hi @bonbonio, are you using HAPI? If so then https://github.com/hapijs/yar would be the way to achieve what you want.

If I misunderstood your question just let me know. Thanks

**Comment by bonbonio** [comment]
Hi, this looks like it, thank you.

Is iron still very new? I am having trouble finding much in the way of examples; but it seems to solve the problem of allowing a user to authenticate in my App, and avoid the need for the getInitialProps in _app.jsx to work.

Are there any other good resources/tutorials for this? Perhaps they could be added to this projects docs too - if this is stated to be the best practice auth for NextJS I feel that would rapidly help people adopt it.

Many thanks though, I think I can dig through yar now.

**Comment by vvo** [comment]
Hi there, I am not sure to fully understand if you're a user of Next.js or [HAPI](https://hapi.dev/) but:
- There's a full example on how to use this module with Next.js: https://github.com/vvo/next-iron-session/tree/master/examples/next.js
- If you're using Hapi, then you should not use this module but rather https://hapi.dev/family/yar/api/
- This module does not handle user registration, only user authentication, that is: once you know who your user is, save this information in a session to then be able to read it again from session

Good luck!

**Comment by bonbonio** [comment]
Hi @vvo , I need to reopen this.

To clarify; as I think you misunderstood my responses. I use NextJS and Hapi, one for FE and one for the API.

- I read through the example numerous times before posting. I tried both `@hapi/yar` and `@hapi/cookie`; I am currently using Yar, but I will switch to cookie later as its supported as an auth strategy in Hapi (This is what i mentioned above). 
- I do also understand this module doesn't handle registration!
- I have a fully functional site and api using JWT auth but I want to replace it with `iron-sessions` so I can get rid of the `getInitialProps` method in my `_app.jsx`.

So with the clarify of that preamble;

I am hitting so many hurdles, this library feels like a solution, but I am surprised that NextJS can have it as best practice authentication when there is minimal documentation – and it would appear a considerable number of gotchas. So I want to help work them out with your help, to fix my issues and then document them for others.

The API is Hapi runs (locally) on http://0.0.0.0:4000, and I a using Yar to set a cookie, and I see the response with the header `set-cookie`. The following is my yar configuration.

hapi; index.js 
````
 {
      plugin: require('@hapi/yar'),
      options: {
        storeBlank: false,
        cookieOptions: {
          password: '32-bit-string-password',
          isSecure: process.env.NODE_ENV === 'production',
        }
      }
    }
````

The NextJS App runs on the typical dev port 0.0.0.0:3000

The header response from the API for /login returns; 

````
Set-Cookie: session=blah 
````

The NextJS site fetches the API using a service wrapped around `axios`, but the cookie does not get set at the client side when I view dev tools on Chrome/Safari/Firefox as I heard someone mention that chrome doesn't like session cookies on ports but that doesn't appear to make any difference as yet.

It might be worth you providing an example of NextJS authenticating with a Hapi API, or we can post all my code when its working, but my current issue is that the session cookie is not set by NextJS. I am unsure if the issue is axios, NextJS or the browser policies for such domains, but I assume you use the same port locally for your own next installation. 

I am intending to write a very complete guide for others to follow, as I feel that NextJS using this authentication method with a Hapi API would be a very common use case - it is just very problematic!
